#!/usr/bin/perl -w
=head1 Name
    Yuan/Program/Bin/bin/gmd.pl
Info
    Author: Yuan-SW-F, yuanswf@163.com
    Created Time: 2017-01-13 13:07:08
    Created Version: gmd.pl 
Usage
    gmd.pl maker.raw.gff assembly.fasta	
=cut
use strict;
use feature qw(say);
use lib '/hwfssz1/ST_AGRIC/LOCAL/Pipline/PL-program/lib';
use Getopt::Long;
my ($help);
GetOptions(
	"help!"=>\$help
);
die opth() if $help;

my $gff=shift;
$gff= `ls *gff`=~/(\S+)/ ? $1 : say "please input annotation.gff !";
my $fasta=shift;
my $genome=fasta($fasta);
open SH,">gff_processing.sh";
my $scp="annotate/script";
print SH "cat $gff|grep -P \"\\tmaker\\t\" >$gff.maker\n
perl $scp/get_AED.pl $gff.maker;
perl $scp\/gff.simple.pl $gff.maker >$gff.maker.sim.gff\n
perl $scp\/getGene.pl $gff.maker.sim.gff $genome >$gff.maker.sim.gff.cds\n
perl $scp\/cds2aa.pl --check $gff.maker.sim.gff.cds >$gff.maker.sim.gff.cds.check\n
perl $scp\/maker_filter.pl $gff.maker.sim.gff $gff.maker.sim.gff.cds.check >$gff.maker.sim.complete.filter_cds.gff
perl $scp\/maker_filter.pl $gff.maker.sim.complete.filter_cds.gff bad0.75.list > $gff.maker.sim.complete.filter_cds_AED.gff
perl $scp\/getGene.pl $gff.maker.sim.complete.filter_cds_AED.gff $genome >$gff.maker.sim.complete.filter_cds_AED.gff.cds
perl $scp\/cds2aa.pl $gff.maker.sim.complete.filter_cds_AED.gff.cds >$gff.maker.sim.complete.filter_cds_AED.gff.pep\n";
