#!/share/app/perl-5.22.0/bin/perl -w
=head1 Name
    tem_prog/len.pl
Info
    Author: Yuan-SW-F, yuanswf@163.com
    Created Time: 2016-10-27 16:27:52
Usage
    len.pl	
=cut
use strict;
use feature qw(say);
use MCsub;
use Getopt::Long;
my ($help);
GetOptions(
	"help!"=>\$help
);
die opth() if $help;

my $str=shift;
say length($str);
