#!/usr/bin/perl -w
=head1 Name
    Program/Bin/bin/miss.pl
Info
    Author: Yuan-SW-F, yuanswf@163.com
    Created Time: 2017-01-19 11:20:49
    Created Version: miss.pl
Usage
    miss.pl	
=cut
use strict;
use feature qw(say);
use MCsub;
use Getopt::Long;
my ($help);
GetOptions(
	"help!"=>\$help
);
die opth() if $help;

my $f=shift;
my %h=inhash($f);
open I,shift;
while (<I>){
/^(\S+)/;
print $_ if !exists $h{$1};
}
