#!/usr/bin/perl -w
#########################################################################
# File Name: nogapscf.pl
# Author: Yuan-SW-F
# mail: yuanswf@163.com
# Created Time: Thu 05 May 2016 09:30:21 AM CST
#########################################################################
use strict;

my $min_length = 0;
my $name = '';
my $seq = '';
my $file=shift;
open IN,"$file"||$!;
open OUT,">./$file.ctg"||$!;
while(<IN>){
   if(/^>(\S+)/){
      &print_scafftig($name, $seq) if($seq);
      $name = $1;
      $seq  = '';
   } else {
      chomp;
      $seq .= $_;
   }
}
&print_scafftig($name, $seq) if($seq);

1;

sub print_scafftig {
   my $name = shift;
   my $seq  = shift;
   my $temp = $seq;
   my $id = 1;
   my $flag = 0;
   my $pos = 1;
   while($seq=~/([ATGCatgc]+)/g){
   my $s = $1;
   if($flag==1){
      if($temp=~/([ATGCatgc]+[Nn]+)/g){
         my $g = $1;
         $pos+=length($g);
      }
   }
   else{$flag=1;}
   next if(length($s) < $min_length);
   print OUT ">$name\_$id  start=$pos  length=".length($s)."\n";
   while($s=~/(.{1,60})/g){
      print OUT "$1\n";
   }
   $id++;
}
}
close IN;
close OUT;

